#!/usr/bin/env python3
"""ROUND 6-P: independent re-encoding + mass certification of the rank-1 stratum at n = 4.

Family (from the definition): A = I + u v^T in GL(4,F); pick i with v_i != 0, scale so v_i = 1;
R = A[!=i,:] = [x, e1+y1 x, e2+y2 x, e3+y3 x], x = (a,b,c) = the other three coordinates of u,
y = (y1,y2,y3) = the other coordinates of v.  (T_3) for R with column j and ordering tau of the other
three columns: D_{j,tau} = det[c_j, M c_j, M^2 c_j].  Deflation (Lean cyclic_standardBasis_of_principalBlock):
D != 0  ==>  e_i is Krylov-cyclic for A P_sigma  ==>  A P_sigma is cyclic (Lean minpoly_eq_charpoly_of_...).
Claim to certify: the ideal J generated by ALL 24 determinants D_{j,tau} (j = 0..3) in Z[a,b,c,y1,y2,y3]
is the unit ideal over Q and over GF(p) -- then for every (x,y) some determinant is nonzero, and the
rank-1 stratum of Kourovka 16.95 at n = 4 holds in that characteristic (no invertibility or x != 0
hypothesis even needed).
Engine: msolve (~/.local/bin/msolve), variable order y3,y2,y1,c,b,a (different from N4k's).
Controls that must NOT be [1]: (i) 3 of the determinants; (ii) the wrong family R' = [x, e1+y1x, e2+y2x, e3]
(whatever its ideal is, it is printed); (iii) the toy <xy, 1-tx>.
Then: all primes p < PMAX (default 10000) for J (msolve per prime, coefficients reduced mod p here)."""
import sys, os, re, itertools, time, subprocess
from pathlib import Path
sys.stdout.reconfigure(line_buffering=True)
import sympy as sp
T0 = time.time()
PMAX = int(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1].isdigit() else 10000
HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
out_arg = sys.argv[sys.argv.index("--out") + 1] if "--out" in sys.argv else None
S = str(Path(out_arg) if out_arg else REPO / "certificates/generated/line/rank1")
os.makedirs(S, exist_ok=True)
MS = os.environ.get("MSOLVE", "msolve")
ENV = dict(os.environ)
a, b, c, y1, y2, y3 = sp.symbols('a b c y1 y2 y3')
VARS = [y3, y2, y1, c, b, a]           # deliberately different order
def family(x, ys, wrong=False):
    cols = [x]
    for j in range(3):
        e = sp.Matrix([1 if k == j else 0 for k in range(3)])
        cols.append(e if (wrong and j == 2) else e + ys[j]*x)
    return cols
def dets_of(cols):
    out = {}
    for j in range(4):
        others = [k for k in range(4) if k != j]
        for tau in itertools.permutations(others):
            M = sp.Matrix.hstack(*[cols[k] for k in tau]); bj = cols[j]
            out[(j, tau)] = sp.expand(sp.Matrix.hstack(bj, M*bj, M*M*bj).det())
    return out
x = sp.Matrix([a, b, c]); ys = [y1, y2, y3]
D = dets_of(family(x, ys)); Dnz = [d for d in D.values() if d != 0]
print("24 determinants, %d nonzero (j=0 gives the F1 pair +-S*Q)" % len(Dnz))
def to_msolve(polys, char, path):
    def red(pl):
        if char == 0: return pl
        pl = sp.Poly(pl, *VARS)
        return sp.Poly({m: (int(cf) % char) for m, cf in pl.terms() if int(cf) % char}, *VARS).as_expr() if any(int(cf) % char for _, cf in pl.terms()) else sp.Integer(0)
    body = []
    for pl in polys:
        q = red(pl)
        if q == 0: continue
        body.append(str(q).replace("**", "^"))
    if not body: body = ["0"]
    open(path, "w").write(",".join(str(v) for v in VARS) + "\n" + str(char) + "\n" + ",\n".join(body) + "\n")
def gb(path):
    out = path + ".gb"
    subprocess.run([MS, "-g", "2", "-v", "0", "-t", "1", "-f", path, "-o", out], env=ENV, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=600)
    body = "".join(l for l in open(out) if not l.startswith("#")).replace("\n", "").replace(" ", "")
    return body
# --- main ideal over Q and small primes, with controls
to_msolve(Dnz, 0, S + "/J_p0.ms"); r = gb(S + "/J_p0.ms"); print("J over Q: %s" % (r[:12]))
to_msolve(Dnz[:3], 0, S + "/ctrl_sub3_p0.ms"); r = gb(S + "/ctrl_sub3_p0.ms"); print("control sub3 over Q: unit=%s (basis length %d chars)" % (r.startswith("[1]"), len(r)))
Dw = [d for d in dets_of(family(x, ys, wrong=True)).values() if d != 0]
to_msolve(Dw, 0, S + "/ctrl_wrong_p0.ms"); r = gb(S + "/ctrl_wrong_p0.ms"); print("control wrong-family over Q: unit=%s (basis %s...)" % (r.startswith("[1]"), r[:40]))
open(S + "/toy.ms", "w").write("x,y,t\n0\nx*y,\n1-t*x\n"); r = gb(S + "/toy.ms"); print("control toy <xy,1-tx>: unit=%s (%s)" % (r.startswith("[1]"), r[:30]))
# --- all primes below PMAX
def primes(n):
    s = bytearray([1])*(n+1); s[0]=s[1]=0
    for i in range(2, int(n**0.5)+1):
        if s[i]: s[i*i::i] = bytearray(len(s[i*i::i]))
    return [i for i in range(n+1) if s[i]]
P = primes(PMAX); ok = []; bad = []
for p in P:
    to_msolve(Dnz, p, S + "/J_p%d.ms" % p)
    r = gb(S + "/J_p%d.ms" % p)
    (ok if r.startswith("[1]") else bad).append(p)
    if len(ok) + len(bad) in (12, 100, 500, 1000):
        print("  ... %d primes done, bad so far: %s [%.0fs]" % (len(ok)+len(bad), bad, time.time()-T0))
print("primes below %d: %d certified [1]; NOT unit: %s" % (PMAX, len(ok), bad))
print("done %.1fs" % (time.time()-T0))
