#!/usr/bin/env python3
"""ROUND 6-AU (registry R6.112a): the deflation (Krylov-determinant) ideal J_n for the RANK-ONE stratum, general n.
Family (from the definition, as in round6_rank1_certify.py for n = 4): A = I + u v^T in GL(n,F); pick i with v_i != 0,
scale so v_i = 1; R = A with row i deleted = [x, e_1 + y_1 x, ..., e_{n-1} + y_{n-1} x] ((n-1) x n), x = the other n-1
coordinates of u, y = the other n-1 coordinates of v.  For a column j of R and an ordering tau of the other n-1
columns, M = [c_tau(1) ... c_tau(n-1)] ((n-1) x (n-1)) and D_{j,tau} = det[c_j, M c_j, ..., M^{n-2} c_j].
Deflation (Lean cyclic_standardBasis_of_principalBlock, any n): D_{j,tau} != 0  ==>  e_i is a cyclic vector of A P_sigma
for the permutation sigma determined by (j, tau)  ==>  A P_sigma cyclic.  So if the ideal J_n generated by ALL
n * (n-1)! determinants is the unit ideal over GF(p) (resp. Q), the rank-one stratum of Kourovka 16.95 at this n holds
in characteristic p (resp. 0).  n = 4 (24 determinants, 6 variables) reproduces round6_rank1_certify.py (sanity).
Controls that must NOT be [1]: the first 3 determinants only; the identity-like wrong family (last basis vector
without the y x term) is printed whatever it is.
Engine: msolve, ONE process at a time, wall --wall s (default 900), swap must be < 9 GB at launch.
Usage: round6_rank1_n5.py <n> <p,p,...> [--wall 900] [--out DIR]"""
import sys, os, re, itertools, time, subprocess
sys.stdout.reconfigure(line_buffering=True)
import sympy as sp
from sympy import Poly, QQ
T0 = time.time()
argv = sys.argv[1:]; wall = 900; out = None
for flag in ("--wall", "--out"):
    if flag in argv:
        k = argv.index(flag); val = argv[k + 1]; argv = argv[:k] + argv[k + 2:]
        if flag == "--wall": wall = int(val)
        else: out = val
n = int(argv[0]); PRIMES = [int(x) for x in argv[1].split(",")]
OUT = out or os.path.dirname(os.path.abspath(__file__))
os.makedirs(OUT, exist_ok=True)
MS = os.path.expanduser("~/.local/bin/msolve"); ENV = dict(os.environ, DYLD_LIBRARY_PATH=os.path.expanduser("~/.local/lib"))
m = n - 1
xs = sp.symbols("x1:%d" % (m + 1)); ys = sp.symbols("y1:%d" % (m + 1))
VARS = list(ys) + list(xs)
def P(e): return Poly(e, *VARS, domain=QQ)
ZERO = P(0); ONE = P(1)
def columns(wrong=False):
    cols = [[P(x) for x in xs]]
    for j in range(m):
        col = [P(1 if k == j else 0) for k in range(m)]
        if not (wrong and j == m - 1):
            col = [col[k] + P(ys[j]) * P(xs[k]) for k in range(m)]
        cols.append(col)
    return cols
def matvec(M, v):  # M: list of columns (each a list of m Polys); v: list of m Polys
    return [sum((M[c][r] * v[c] for c in range(m)), ZERO) for r in range(m)]
def det(mat):  # mat: list of m column-vectors of Polys; Laplace along the first column (m <= 4: fine)
    k = len(mat)
    if k == 1: return mat[0][0]
    total = ZERO
    for r in range(k):
        if mat[0][r] == ZERO: continue
        minor = [[col[s] for s in range(k) if s != r] for col in mat[1:]]
        term = mat[0][r] * det(minor)
        total = total + term if r % 2 == 0 else total - term
    return total
def dets_of(cols):
    D = []
    for j in range(n):
        others = [k for k in range(n) if k != j]
        for tau in itertools.permutations(others):
            M = [cols[k] for k in tau]; b = cols[j]
            kry = [b]
            for _ in range(m - 1): kry.append(matvec(M, kry[-1]))
            D.append(det(kry))
    return D
cols = columns(); D = dets_of(cols); Dnz = [d for d in D if d != ZERO]
print("n=%d: %d determinants, %d nonzero, max terms %d, max degree %d  [%.0fs]" % (n, len(D), len(Dnz), max(len(d.terms()) for d in Dnz), max(d.total_degree() for d in Dnz), time.time() - T0))
def to_msolve(polys, char, path):
    body = []
    for pl in polys:
        if char:
            terms = {mon: int(cf) % char for mon, cf in pl.terms() if int(cf) % char}
            if not terms: continue
            q = Poly(terms, *VARS, domain=QQ)
        else: q = pl
        body.append(str(q.as_expr()).replace("**", "^"))
    if not body: body = ["0"]
    open(path, "w").write(",".join(str(v) for v in VARS) + "\n" + str(char) + "\n" + ",\n".join(body) + "\n")
def swap_mb():
    mm = re.search(r"used = ([\d.]+)M", subprocess.run(["sysctl", "vm.swapusage"], capture_output=True, text=True).stdout)
    return float(mm.group(1)) if mm else 0.0
def gb(path):
    while swap_mb() > 9000: print("  swap %.0f MB > 9000, waiting" % swap_mb()); time.sleep(30)
    o = path + ".gb"
    if os.path.exists(o): os.remove(o)
    t0 = time.time()
    try:
        r = subprocess.run([MS, "-g", "2", "-v", "0", "-t", "1", "-f", path, "-o", o], env=ENV, capture_output=True, text=True, timeout=wall)
    except subprocess.TimeoutExpired:
        return None, time.time() - t0
    if r.returncode != 0 or not os.path.exists(o): return None, time.time() - t0
    body = "".join(l for l in open(o) if not l.startswith("#")).replace("\n", "").replace(" ", "")
    return body, time.time() - t0
for p in PRIMES:
    path = OUT + "/J%d_p%d.ms" % (n, p); to_msolve(Dnz, p, path)
    r, s = gb(path)
    print("J_%d over %s: %s  (%.0fs)" % (n, "Q" if p == 0 else "GF(%d)" % p, "NORESULT/capped" if r is None else ("UNIT [1]" if r.startswith("[1]") else "NOT unit (basis %d chars: %s...)" % (len(r), r[:60])), s))
    cpath = OUT + "/ctrl_sub3_p%d.ms" % p; to_msolve(Dnz[:3], p, cpath); r, s = gb(cpath)
    print("  control 3 determinants: %s (expected NOT unit)" % ("NORESULT" if r is None else ("UNIT" if r.startswith("[1]") else "NOT unit")))
print("done %.0fs" % (time.time() - T0))
