import K1695.TranspositionLemmaFull
import K1695.CyclicToMinpoly

open scoped Matrix

namespace K1695

open Matrix Polynomial

variable {F L : Type*} [Field F] [Field L] [Algebra F L]

/-- The transposition vector commutes with extension of scalars. -/
theorem map_transpositionVector {n : ℕ} (a b : Fin n) :
    (fun i => algebraMap F L (transpositionVector (K := F) a b i)) =
      transpositionVector (K := L) a b := by
  classical
  ext i
  by_cases hia : i = a <;> by_cases hib : i = b <;>
    simp_all [transpositionVector]

/-- Distinct indices give a nonzero transposition vector over every field. -/
theorem transpositionVector_ne_zero {n : ℕ} (a b : Fin n) (hab : a ≠ b) :
    transpositionVector (K := F) a b ≠ 0 := by
  intro h
  have ha := congrFun h a
  simp [transpositionVector, hab] at ha

/-- An element of minimal-polynomial degree two is not in the base field. -/
theorem not_mem_algebraMap_range_of_minpoly_natDegree_two (μ : L)
    (hdeg : (minpoly F μ).natDegree = 2) :
    μ ∉ Set.range (algebraMap F L) := by
  rintro ⟨a, rfl⟩
  rw [minpoly.eq_X_sub_C L a] at hdeg
  simp at hdeg

/-- A two-dimensional power basis generated by `μ` supplies the coordinate
decomposition required by quadratic descent. -/
theorem quadratic_decomposition_of_powerBasis {n : ℕ} (μ : L)
    (pb : PowerBasis F L) (hgen : pb.gen = μ) (hdim : pb.dim = 2)
    (z : Fin n → L) : ∃ z₀ z₁ : Fin n → F,
      z = fun i => algebraMap F L (z₀ i) + μ * algebraMap F L (z₁ i) := by
  let e : Fin 2 ≃ Fin pb.dim := finCongr hdim.symm
  refine ⟨fun i => pb.basis.repr (z i) (e 0),
    fun i => pb.basis.repr (z i) (e 1), ?_⟩
  ext i
  have hrepr := pb.basis.sum_repr (z i)
  have hrepr' : ∑ j : Fin 2,
      pb.basis.repr (z i) (e j) • pb.basis (e j) = z i :=
    (e.sum_comp (fun j => pb.basis.repr (z i) j • pb.basis j)).trans hrepr
  rw [Fin.sum_univ_two] at hrepr'
  simpa [e, pb.basis_eq_pow, hgen, Algebra.smul_def, mul_comm] using hrepr'.symm

/-- A quadratic annihilator of a matrix also annihilates its transpose. -/
theorem quadratic_annihilator_transpose {n : ℕ}
    (A : Matrix (Fin n) (Fin n) F) (s t : F)
    (hzero : A * A - t • A - s • 1 = 0) :
    A.transpose * A.transpose - t • A.transpose - s • 1 = 0 := by
  have h := congrArg Matrix.transpose hzero
  simpa [Matrix.transpose_sub, Matrix.transpose_mul, Matrix.transpose_smul] using h

/-- Every monic quadratic has the coefficient convention used by the
quadratic descent lemma. -/
theorem monic_quadratic_normal_form (m : F[X]) (hmonic : m.Monic)
    (hdeg : m.natDegree = 2) :
    m = Polynomial.X ^ 2 - Polynomial.C (-m.coeff 1) * Polynomial.X -
      Polynomial.C (-m.coeff 0) := by
  have hc2 : m.coeff 2 = 1 := by
    rw [← hdeg]
    exact hmonic.coeff_natDegree
  ext k
  by_cases hk : k ≤ 2
  · interval_cases k <;> simp [hc2]
  · have hlt : m.natDegree < k := by omega
    rw [m.coeff_eq_zero_of_natDegree_lt hlt]
    symm
    apply Polynomial.coeff_eq_zero_of_natDegree_lt
    have hqdeg :
        (Polynomial.X ^ 2 - Polynomial.C (-m.coeff 1) * Polynomial.X -
          Polynomial.C (-m.coeff 0)).natDegree ≤ 2 := by
      compute_degree
    omega

/-- A root of a monic quadratic satisfies the scalar relation expected by
the descent lemma, with coefficients read directly from the polynomial. -/
theorem quadratic_relation_of_root (m : F[X]) (hmonic : m.Monic)
    (hdeg : m.natDegree = 2) (μ : L)
    (hroot : Polynomial.IsRoot (m.map (algebraMap F L)) μ) :
    μ * μ = algebraMap F L (-m.coeff 0) +
      algebraMap F L (-m.coeff 1) * μ := by
  have hmform := monic_quadratic_normal_form m hmonic hdeg
  rw [Polynomial.IsRoot, Polynomial.eval_map, hmform] at hroot
  simp at hroot
  simp only [map_neg]
  linear_combination hroot

/-- If the displayed monic quadratic is the matrix minimal polynomial, its
evaluation at the matrix is zero. -/
theorem quadratic_annihilator_of_minpoly {n : ℕ}
    (A : Matrix (Fin n) (Fin n) F) (s t : F)
    (hmin : minpoly F A =
      Polynomial.X ^ 2 - Polynomial.C t * Polynomial.X - Polynomial.C s) :
    A * A - t • A - s • 1 = 0 := by
  have h := minpoly.aeval F A
  rw [hmin] at h
  simpa [pow_two, Algebra.algebraMap_eq_smul_one] using h

/-- The hard quadratic-descent calculation excludes a base-field
transposition vector from the column space, provided coordinates in the
power basis `1, μ` are supplied. -/
theorem quadratic_descent_transposition_not_mem_range {n : ℕ}
    (B : Matrix (Fin n) (Fin n) F) (μ : L)
    (hμbase : μ ∉ Set.range (algebraMap F L)) (s t : F)
    (hquad : μ * μ = algebraMap F L s + algebraMap F L t * μ)
    (hdecomp : ∀ z : Fin n → L, ∃ z₀ z₁ : Fin n → F,
      z = fun i => algebraMap F L (z₀ i) + μ * algebraMap F L (z₁ i))
    (hzero : B * B - t • B - s • 1 = 0)
    (a b : Fin n) (hab : a ≠ b) :
    transpositionVector (K := L) a b ∉
      LinearMap.range
        (B.map (algebraMap F L) - μ • 1).mulVecLin := by
  intro hmem
  rcases hmem with ⟨z, hzE⟩
  obtain ⟨z₀, z₁, hz⟩ := hdecomp z
  let d : Fin n → F := transpositionVector (K := F) a b
  have heq : (B.map (algebraMap F L) - μ • 1).mulVec z =
      fun i => algebraMap F L (d i) := by
    simpa only [Matrix.mulVecLin_apply, d, map_transpositionVector (F := F) (L := L)]
      using hzE
  obtain ⟨v, hv⟩ := l7_quadratic_descent_with_decomposition
    B μ hμbase s t hquad d z₀ z₁ z hz heq
  have hd0 : d = 0 := by
    rw [hzero, Matrix.zero_mulVec] at hv
    exact hv
  exact (transpositionVector_ne_zero (F := F) a b hab) hd0

/-- Rank-form stratum-(b) conclusion at a quadratic root.  This theorem
formalizes the two T4 transversality arguments and corrected T2.  The two
currently missing bridges are explicit: quadratic power-basis coordinates
for every extension vector and the root-nullity equality `rank = 2`. -/
theorem stratumB_rank_at_quadratic_root_with_hypotheses
    (A : Matrix (Fin 4) (Fin 4) F) (_hA : IsUnit A.det)
    (m : F[X]) (_hm : Irreducible m) (_hdeg : m.natDegree = 2)
    (hmin : minpoly F A = m)
    (μ : L) (hμbase : μ ∉ Set.range (algebraMap F L)) (hμ : μ ≠ 0)
    (s t : F)
    (hmform : m =
      Polynomial.X ^ 2 - Polynomial.C t * Polynomial.X - Polynomial.C s)
    (hquad : μ * μ = algebraMap F L s + algebraMap F L t * μ)
    (hdecomp : ∀ z : Fin 4 → L, ∃ z₀ z₁ : Fin 4 → F,
      z = fun i => algebraMap F L (z₀ i) + μ * algebraMap F L (z₁ i))
    (hnull : (A.map (algebraMap F L) - μ • 1).rank = 2)
    (a b : Fin 4) (hab : a ≠ b) :
    (A.map (algebraMap F L) * transpositionMatrix (K := L) a b - μ • 1).rank = 3 := by
  have hminform : minpoly F A =
      Polynomial.X ^ 2 - Polynomial.C t * Polynomial.X - Polynomial.C s :=
    hmin.trans hmform
  have hzero := quadratic_annihilator_of_minpoly A s t hminform
  have hcol := quadratic_descent_transposition_not_mem_range
    A μ hμbase s t hquad hdecomp hzero a b hab
  have hzeroT := quadratic_annihilator_transpose A s t hzero
  have hrow := quadratic_descent_transposition_not_mem_range
    A.transpose μ hμbase s t hquad hdecomp hzeroT a b hab
  have hrow' : transpositionVector (K := L) a b ∉
      LinearMap.range
        (A.map (algebraMap F L) - μ • 1).transpose.mulVecLin := by
    simpa [Matrix.transpose_sub, Matrix.transpose_map, Matrix.transpose_smul]
      using hrow
  exact l6prime_t2_corrected (A.map (algebraMap F L)) μ a b hab hμ
    (by omega) hnull hcol hrow'

/-- The same rank conclusion written with `Matrix.swap`, the notation used in
the ticket's target theorem. -/
theorem stratumB_rank_at_quadratic_root_swap_with_hypotheses
    (A : Matrix (Fin 4) (Fin 4) F) (hA : IsUnit A.det)
    (m : F[X]) (hm : Irreducible m) (hdeg : m.natDegree = 2)
    (hmin : minpoly F A = m)
    (μ : L) (hμbase : μ ∉ Set.range (algebraMap F L)) (hμ : μ ≠ 0)
    (s t : F)
    (hmform : m =
      Polynomial.X ^ 2 - Polynomial.C t * Polynomial.X - Polynomial.C s)
    (hquad : μ * μ = algebraMap F L s + algebraMap F L t * μ)
    (hdecomp : ∀ z : Fin 4 → L, ∃ z₀ z₁ : Fin 4 → F,
      z = fun i => algebraMap F L (z₀ i) + μ * algebraMap F L (z₁ i))
    (hnull : (A.map (algebraMap F L) - μ • 1).rank = 2)
    (a b : Fin 4) (hab : a ≠ b) :
    (A.map (algebraMap F L) * Matrix.swap L a b - μ • 1).rank = 3 := by
  exact stratumB_rank_at_quadratic_root_with_hypotheses
    A hA m hm hdeg hmin μ hμbase hμ s t hmform hquad hdecomp hnull a b hab

/-- Power-basis version of the rank-form result: coordinate decompositions
are derived rather than assumed vector by vector. -/
theorem stratumB_rank_at_quadratic_root_of_powerBasis_and_nullity
    (A : Matrix (Fin 4) (Fin 4) F) (hA : IsUnit A.det)
    (m : F[X]) (hm : Irreducible m) (hdeg : m.natDegree = 2)
    (hmin : minpoly F A = m)
    (μ : L) (hμbase : μ ∉ Set.range (algebraMap F L)) (hμ : μ ≠ 0)
    (s t : F)
    (hmform : m =
      Polynomial.X ^ 2 - Polynomial.C t * Polynomial.X - Polynomial.C s)
    (hquad : μ * μ = algebraMap F L s + algebraMap F L t * μ)
    (pb : PowerBasis F L) (hgen : pb.gen = μ) (hdim : pb.dim = 2)
    (hnull : (A.map (algebraMap F L) - μ • 1).rank = 2)
    (a b : Fin 4) (hab : a ≠ b) :
    (A.map (algebraMap F L) * Matrix.swap L a b - μ • 1).rank = 3 := by
  apply stratumB_rank_at_quadratic_root_swap_with_hypotheses
    A hA m hm hdeg hmin μ hμbase hμ s t hmform hquad
      (fun z => quadratic_decomposition_of_powerBasis μ pb hgen hdim z) hnull a b hab

/-- Simple-extension version.  A degree-two integral generator supplies the
power basis automatically.  The only substantive stratum-(b) bridge still
assumed here is the root-nullity equality. -/
theorem stratumB_rank_at_quadratic_root_of_adjoin_eq_top_and_nullity
    (A : Matrix (Fin 4) (Fin 4) F) (hA : IsUnit A.det)
    (m : F[X]) (hm : Irreducible m) (hdeg : m.natDegree = 2)
    (hmin : minpoly F A = m)
    (μ : L) (hμint : IsIntegral F μ)
    (hadjoin : Algebra.adjoin F ({μ} : Set L) = ⊤)
    (hμdeg : (minpoly F μ).natDegree = 2)
    (s t : F)
    (hmform : m =
      Polynomial.X ^ 2 - Polynomial.C t * Polynomial.X - Polynomial.C s)
    (hquad : μ * μ = algebraMap F L s + algebraMap F L t * μ)
    (hnull : (A.map (algebraMap F L) - μ • 1).rank = 2)
    (a b : Fin 4) (hab : a ≠ b) :
    (A.map (algebraMap F L) * Matrix.swap L a b - μ • 1).rank = 3 := by
  let pb : PowerBasis F L := PowerBasis.ofAdjoinEqTop hμint hadjoin
  have hμbase := not_mem_algebraMap_range_of_minpoly_natDegree_two μ hμdeg
  have hμ : μ ≠ 0 := by
    intro hzero
    apply hμbase
    exact ⟨0, by simp [hzero]⟩
  apply stratumB_rank_at_quadratic_root_of_powerBasis_and_nullity
    A hA m hm hdeg hmin μ hμbase hμ s t hmform hquad pb
  · exact PowerBasis.ofAdjoinEqTop_gen hμint hadjoin
  · simpa only [pb, PowerBasis.ofAdjoinEqTop_dim] using hμdeg
  · exact hnull
  · exact hab

/-- Clean root-field interface for the proved rank statement.  Polynomial
coefficients, the quadratic relation, non-rationality, nonzeroness, and all
power-basis decompositions are derived internally.  `hnull` is the sole
stratum-specific spectral hypothesis left explicit. -/
theorem stratumB_rank_at_root_of_simple_extension_and_nullity
    (A : Matrix (Fin 4) (Fin 4) F) (hA : IsUnit A.det)
    (m : F[X]) (hm : Irreducible m) (hdeg : m.natDegree = 2)
    (hmin : minpoly F A = m)
    (μ : L) (hμint : IsIntegral F μ)
    (hadjoin : Algebra.adjoin F ({μ} : Set L) = ⊤)
    (hμdeg : (minpoly F μ).natDegree = 2)
    (hroot : Polynomial.IsRoot (m.map (algebraMap F L)) μ)
    (hnull : (A.map (algebraMap F L) - μ • 1).rank = 2)
    (a b : Fin 4) (hab : a ≠ b) :
    (A.map (algebraMap F L) * Matrix.swap L a b - μ • 1).rank = 3 := by
  have hmonic : m.Monic := by
    rw [← hmin]
    exact minpoly.monic (Algebra.IsIntegral.isIntegral A)
  let s : F := -m.coeff 0
  let t : F := -m.coeff 1
  have hmform : m =
      Polynomial.X ^ 2 - Polynomial.C t * Polynomial.X - Polynomial.C s := by
    simpa only [s, t] using monic_quadratic_normal_form m hmonic hdeg
  have hquad : μ * μ = algebraMap F L s + algebraMap F L t * μ := by
    simpa only [s, t] using quadratic_relation_of_root m hmonic hdeg μ hroot
  exact stratumB_rank_at_quadratic_root_of_adjoin_eq_top_and_nullity
    A hA m hm hdeg hmin μ hμint hadjoin hμdeg s t hmform hquad hnull a b hab

#print axioms map_transpositionVector
#print axioms transpositionVector_ne_zero
#print axioms not_mem_algebraMap_range_of_minpoly_natDegree_two
#print axioms quadratic_decomposition_of_powerBasis
#print axioms quadratic_annihilator_transpose
#print axioms monic_quadratic_normal_form
#print axioms quadratic_relation_of_root
#print axioms quadratic_annihilator_of_minpoly
#print axioms quadratic_descent_transposition_not_mem_range
#print axioms stratumB_rank_at_quadratic_root_with_hypotheses
#print axioms stratumB_rank_at_quadratic_root_swap_with_hypotheses
#print axioms stratumB_rank_at_quadratic_root_of_powerBasis_and_nullity
#print axioms stratumB_rank_at_quadratic_root_of_adjoin_eq_top_and_nullity
#print axioms stratumB_rank_at_root_of_simple_extension_and_nullity

end K1695
